config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :therapists
  resources :therapists, only: %i[index] do
    collection do
      get :profile
      delete :delete
    end
  end
  resources :statuses, only: %i[create]
  resources :consultations

  resources :patients, only: %i[show] do
    member do
      delete :remove
    end
    collection do
      get :create_fake
    end
  end

  root 'therapists#home'

  namespace :api, defaults: { format: 'json' } do
    mount_devise_token_auth_for 'Patient', at: 'auth', controllers: {
      registrations: 'api/registrations',
      sessions: 'api/sessions'
      # passwords: 'study_quizz/passwords'
    }
    resources :entries
    resources :therapists, only: %i[show] do
      member do
        get :add
      end
    end
    resources :categories, only: %i[index create destroy]
  end
end

app/models/therapist.rb
# frozen_string_literal: true

class Therapist < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

  has_many :patients, dependent: :nullify
  has_many :consultations, dependent: :destroy
end

app/controllers/api/therapists_controller.rb
# frozen_string_literal: true

module Api
  class TherapistsController < ApiController
    before_action :set_user
    before_action :set_therapist

    def show; end

    def add
      @patient.update(therapist: @therapist)
      render json: { message: 'success' }, status: :created
    end

    private

    def set_therapist
      @therapist = Therapist.find(params[:id])
    end

    def set_user
      @patient = current_api_patient
    end
  end
end

app/controllers/therapists_controller.rb
# frozen_string_literal: true

#:nodoc:
class TherapistsController < TherapistsApplicationController
  skip_before_action :authenticate_therapist!, only: [:home]
  skip_before_action :set_therapist, only: [:home]

  def home
    redirect_to therapists_path unless current_therapist&.id.nil?
  end

  def index
    @patients = @therapist.patients.includes(:statuses)
  end

  def profile
    @qr_code = RQRCode::QRCode.new(@therapist.id.to_s)
    @svg_qr = @qr_code.as_svg
  end

  def delete
    @therapist.destroy
    redirect_to root_path
  end
end

app/helpers/therapist_helper.rb
# frozen_string_literal: true

#:noeoc:
module TherapistHelper
end

app/views/therapists/_listing.html.erb
<div class="d-flex flex-wrap justify-content-center">
  <% @patients.each do |patient| %>
    <%= render partial: 'therapists/patient', locals: { patient: patient} %>
  <% end %>
</div>

app/views/therapists/_patient.html.erb
<div class="border-bottom m-2" style="width: 250px">
  <div class="d-flex flex-column">
    <div class="d-flex justify-content-between border w-100">
      <p>Contact: </p>
      <p><%= "#{patient.first_name} #{patient.last_name}" %></p>
    </div>
    <div class="d-flex justify-content-between border w-100">
      <p>Status: </p>
      <%= form_with url: statuses_url, method: :post, local: true, id: 'status_form' do |form| %>
        <%= form.select(:status, options_for_select(['', *Global::STATUS], patient.statuses.last&.title), {}, { onchange: "submitForm(this)"} ) %>
        <%= form.hidden_field(:patient, value: patient.id) %>
      <% end %>
    </div>
    <div class="d-flex justify-content-between border w-100">
      <p>Dernière MAJ: </p>
      <p><%= patient.statuses.last.present? ? distance_of_time_in_words(patient.statuses.last.created_at, DateTime.now) : 'N/A' %></p>
    </div>
    <div class="align-self-end border w-100">
      <%= link_to "Voir le profil", patient_path(patient), class: "btn btn-outline-secondary w-100" %>
    </div>
  </div>
</div>

app/views/therapists/home.html.erb
<h1>Salut à toi jeune entrepreneur</h1>

<h3>Si tu vois ceci c'est que tu as réussis à accéder au serveur Rails, félicitations !</h3>

<p>Tu veux accéder au site côté thérapeuthe ? <%= link_to 'Viens par ici', root_path %></p>

app/views/therapists/index.html.erb
<h1 class="text-center my-5">Mon tableau de bord</h1>

<% if flash[:notice] %>
  <h2 class="text-center my-5"> <%= flash[:notice] %></h2>
<% end %>

<% if @therapist.patients.any? %>
  <%= area_chart Status.where(patient_id: @patients.pluck(:id)).group(:title).group_by_day(:created_at).count, discrete: true %>
  <%= render partial: "therapists/listing" %>
<% else %>
    <h3 class="text-center">Il faut ajouter des patients pour avoir accès aux données</h3>
<% end %>

<%= link_to 'Ajouter un faux patient', create_fake_patients_path %>
<script>
  function submitForm(selector) {
      selector.parentNode.submit();
  }
</script>

app/views/therapists/profile.html.erb
<h4><%= @therapist.first_name %> <%= @therapist.last_name %></h4>
<h5><%= @therapist.address %></h5>

<h5>Faites scanner ce QR code à vos patients pour vous affilier :</h5>
<%= @svg_qr.html_safe %>
<br/>
<%= link_to 'Me deconnecter', destroy_therapist_session_path, method: :delete, data: { confirm: 'Êtes-vous sûr ?'}, class: "btn btn-outline-danger my-5 mx-2" %>

<%= link_to 'Supprimer mon compte', delete_therapists_path, method: :delete, data: { confirm: 'Êtes-vous sûr ?'}, class: "btn btn-outline-danger" %>