config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :therapists
  resources :therapists, only: %i[index] do
    collection do
      get :profile
      delete :delete
    end
  end
  resources :statuses, only: %i[create]
  resources :consultations

  resources :patients, only: %i[show] do
    member do
      delete :remove
    end
    collection do
      get :create_fake
    end
  end

  root 'therapists#home'

  namespace :api, defaults: { format: 'json' } do
    mount_devise_token_auth_for 'Patient', at: 'auth', controllers: {
      registrations: 'api/registrations',
      sessions: 'api/sessions'
      # passwords: 'study_quizz/passwords'
    }
    resources :entries
    resources :therapists, only: %i[show] do
      member do
        get :add
      end
    end
    resources :categories, only: %i[index create destroy]
  end
end

app/models/consultation.rb
# frozen_string_literal: true

class Consultation < ApplicationRecord
  belongs_to :therapist
  belongs_to :patient
end

app/controllers/consultations_controller.rb
# frozen_string_literal: true

class ConsultationsController < TherapistsApplicationController
  before_action :set_consultation, only: %i[show edit update destroy]

  # GET /sessions
  def index
    @consultations = @therapist.consultations.includes(:patient)
  end

  # GET /sessions/1
  def show
    last_consultation = @consultation.patient.consultations
                                     .where('schedule_time < ?', @consultation.schedule_time)
                                     .order(schedule_time: :desc).first
    @entries = @consultation.patient.entries.where('entries.time < ?', @consultation.schedule_time)
    @entries = @entries.where('entries.time > ?', last_consultation.schedule_time) unless last_consultation.nil?
  end

  # GET /sessions/new
  def new
    @consultation = Consultation.new
  end

  # GET /sessions/1/edit
  def edit; end

  # POST /sessions or /sessions.json
  def create
    @consultation = Consultation.new(consultation_params)
    @consultation.therapist = @therapist
    if @consultation.save
      redirect_to consultations_path, notice: 'Consultation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /sessions/1
  def update
    if @consultation.update(consultation_params)
      redirect_to @consultation, notice: 'Consultation was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /sessions/1
  def destroy
    @consultation.destroy
    redirect_to consultations_url, notice: 'Consultation was successfully destroyed.'
  end

  private

  def set_consultation
    @consultation = Consultation.find(params[:id])
    raise ActiveRecord.RecordInvalid if @consultation.therapist != @therapist
  end

  def consultation_params
    params.require(:consultation).permit(:schedule_time, :patient_id, :note)
  end
end

app/views/consultations/_form.html.erb
<%= simple_form_for @consultation do |f| %>
  <% if consultation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(consultation.errors.count, "error") %> prohibited this consultation from being saved:</h2>
      <ul>
        <% consultation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="w-25">
    <%= f.label :schedule_time, label: 'Date de la consultation' %> <br/>
    <%= render partial: 'layouts/datetimepicker', locals: {name: 'consultation[schedule_time]', value: @consultation.schedule_time} %>
  </div>
  <div>
    <%= f.input :note %>
  </div>
  <div style="width: 15rem;">
    <%= f.input :patient_id, collection: @therapist.patients, selected: params[:consultation_patient_id] %>
  </div>
  <%= f.button :submit, value: 'Valider', class: "btn btn-outline-success m-1" %>
<% end %>

app/views/consultations/_table.html.erb
<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th scope="col" class="text-center">Date de la consultation</th>
    <th scope="col" class="text-center">Patient</th>
    <th scope="col" class="w-25 text-center" >Note</th>
    <th scope="col" colspan="3" class="text-center">Actions</th>
  </tr>
  </thead>
  <tbody>
  <% consultations.each do |consultation| %>
    <tr>
      <td class="text-center"><%= consultation.schedule_time&.strftime("%Y/%m/%d %Hh%M") %></td>
      <td class="text-center"><%= link_to consultation.patient, patient_path(consultation.patient) %></td>
      <td class="w-25 text-center"><%= consultation.note&.truncate(30) %></td>
      <td class="text-center"><%= link_to 'Voir', consultation, class: 'btn btn-outline-primary'  %></td>
      <td class="text-center"><%= link_to 'Modifier', edit_consultation_path(consultation), class: 'btn btn-outline-secondary' %></td>
      <td class="text-center"><%= link_to 'Supprimer', consultation, method: :delete, data: { confirm: "Êtes-vous sûr ? " }, class: 'btn btn-outline-danger' %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/consultations/edit.html.erb
<h1>Modifier la Séance</h1>

<%= render 'form', consultation: @consultation %>

<div class="my-5">
  <%= link_to 'Voir', @consultation, class: "btn btn-outline-primary mx-1" %>
  <%= link_to 'Retour', consultations_path, class: "btn btn-outline-secondary mx-1" %>
</div>

app/views/consultations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scéances à venir</h1>
<%= render partial: 'table', locals: { consultations: @consultations.where('schedule_time > ?', DateTime.now).order(:schedule_time)} %>

<h1>Scéances passées</h1>
<%= render partial: 'table', locals: { consultations: @consultations.where('schedule_time < ?', DateTime.now).order(schedule_time: :desc)} %>

<br>

<%= link_to 'Ajouter une nouvelle séance', new_consultation_path %>

app/views/consultations/new.html.erb
<h1>Nouvelle Séance</h1>

<%= render 'form', consultation: @consultation %>

<%= link_to 'Retour', consultations_path, class: "btn btn-outline-secondary my-5 mx-1" %>

app/views/consultations/show.html.erb
<%= link_to 'Retour', consultations_path, class: "btn btn-outline-secondary mx-1" %>

<p id="notice"><%= notice %></p>

<p>
  <strong>Date de la consultation:</strong>
  <%= @consultation.schedule_time.strftime("%Y/%m/%d %Hh%M") %>
</p>

<p>
  <strong>Note de la scéance:</strong>
  <%= @consultation.note %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @consultation.patient %>
</p>

<%= link_to 'Modifier', edit_consultation_path(@consultation), class: "btn btn-outline-primary mx-1" %>


<% if @entries&.any? %>
  <div class="w-100 py-5">
    <h3>Entrées du patient relatives à la scéance:</h3>
    <div class="d-flex flex-wrap">
      <% @entries.each do |entry| %>
        <div class="border m-3 p-3 entry">
          <p>Location: <%= entry.location %></p>
          <p><%= entry.time.strftime("%Hh%M, %d/%m/%Y") %></p>
          <p class="m-0">
            Context:
          <p class="entry--content">
            <%=  entry.context %>
          </p>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <h3>Aucune entrée à afficher pour cette consultation</h3>
<% end %>