config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :therapists
  resources :therapists, only: %i[index] do
    collection do
      get :profile
      delete :delete
    end
  end
  resources :statuses, only: %i[create]
  resources :consultations

  resources :patients, only: %i[show] do
    member do
      delete :remove
    end
    collection do
      get :create_fake
    end
  end

  root 'therapists#home'

  namespace :api, defaults: { format: 'json' } do
    mount_devise_token_auth_for 'Patient', at: 'auth', controllers: {
      registrations: 'api/registrations',
      sessions: 'api/sessions'
      # passwords: 'study_quizz/passwords'
    }
    resources :entries
    resources :therapists, only: %i[show] do
      member do
        get :add
      end
    end
    resources :categories, only: %i[index create destroy]
  end
end

app/views/layouts/_datetimepicker.html.erb
<script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha512-AIOTidJAcHBH2G/oZv9viEGXRqDNmfdPVPYOYKGy3fti0xIplnlgMHUGfuNRzC6FkzIo0iIxgFnr9RikFxK+sw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<input id="datetimepicker" type="text" name="<%= name %>" value="<% value if value %>">

<script defer>
    $.datetimepicker.setLocale('fr');

    jQuery('#datetimepicker').datetimepicker({
        minDate: 0,
        step: 30,
        <% if value %>
          value: "<%= value.strftime("%Y/%m/%d %T")%>",
        <% end %>
    });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Minders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="d-flex justify-content-lg-between px-5 my-1 align-items-center shadow">
    <h1>Minders</h1>
    <div class="w-50 d-flex justify-content-around">
      <% if current_therapist&.id.nil? %>
        <%= link_to 'Home', root_path %>
        <%=  link_to 'Connexion', new_therapist_session_path  %>
        <%=  link_to 'Inscription', new_therapist_registration_path  %>
      <%  else  %>
        <%= link_to 'Tableau de bord', root_path %>
        <%=  link_to 'Mes séances', consultations_path %>
        <%=  link_to 'Mon compte', profile_therapists_path  %>
      <%  end %>
    </div>
  </header>
  <div class="p-5">
    <%= yield %>
  </div>
  </body>
</html>